name: ci-cd-staging

on:
  pull_request:
    branches: "main"

jobs:
  test:
    environment: staging
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.x
      - name: Setup panpm
        uses: pnpm/action-setup@v6.0.9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup Turborepo Remote Cache
        uses: vercel/setup-turborepo-remote-cache-action@v1.0.0
      - name: Run Tests
        run: pnpm turbo test
