name: ci-cd-staging

on:
  pull_request:
    branches: "main"

jobs:
  test:
    environment: staging
    runs-on: ubuntu-24.04
    steps:
      - name: project_setup
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: node_setup
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24.x
      - name: node_validation
        run: node -v
      - name: pnpm_setup
        uses: pnpm/action-setup@v6.0.9
      - name: pnpm_validation
        run: pnpm -v
